quarkus.http.port=${HTTP_PORT:8080}

quarkus.log.console.color=false

mp.messaging.outgoing.chat-out.acks=all
mp.messaging.outgoing.chat-out.connector=smallrye-kafka
mp.messaging.outgoing.chat-out.topic=chat.messages
mp.messaging.outgoing.chat-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
#mp.messaging.incoming.chat-in.value.deserializer.type=org.acme.chat.Message
#mp.messaging.outgoing.chat-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

#%prod.mp.messaging.outgoing.chat-out.bootstrap.servers=${KAFKA_BOOTSTRAP:localhost:9092}

mp.messaging.incoming.chat-in.connector=smallrye-kafka
mp.messaging.incoming.chat-in.topic=chat.messages

# unique group can be set using POD_NAME for example
# whe deployed to k8s cluster using metadata.name. See example below.
# kafka.group.id=chat-delivery-service-${POD_NAME}
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: my-quarkus-service
# spec:
#   # ... (replica configuration, etc.)
#   template:
#     spec:
#       containers:
#       - name: quarkus-container
#         image: your-quarkus-image:1.0.0
#         env:
#           # This line injects the unique Pod name into an environment variable named POD_NAME
#           - name: POD_NAME
#             valueFrom:
#               fieldRef:
#                 fieldPath: metadata.name

# The other option is to use UUID
kafka.group.id=chat-delivery-service-${quarkus.uuid}
# mp.messaging.incoming.chat-in.group.id=chat-delivery-service-${quarkus.uuid}
#mp.messaging.incoming.chat-in.value.deserializer=io.quarkus.kafka.client.serialization.ObjectMapperDeserializer
#mp.messaging.incoming.chat-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
#%prod.mp.messaging.incoming.chat-in.bootstrap.servers=${KAFKA_BOOTSTRAP:localhost:9092}

mp.messaging.incoming.participant-created.connector=smallrye-kafka
mp.messaging.incoming.participant-created.topic=chat.participants.created

mp.messaging.incoming.participant-removed.connector=smallrye-kafka
mp.messaging.incoming.participant-removed.topic=chat.participants.removed

%prod.kafka.bootstrap.servers=${KAFKA_BOOTSTRAP:localhost:9092}

quarkus.log.console.level=TRACE
quarkus.log.level=INFO

#========  JWT Verification Configuration ================
smallrye.jwt.verify.secretkey=${JWT_JWK}
#smallrye.jwt.verify.key.location=classpath:jwt_secret.jwk
mp.jwt.verify.publickey.algorithm=HS256
# Must match 'iss' claim in your BFF-generated token
mp.jwt.verify.issuer=chat-web

# Subprotocol workaround for JS clients
quarkus.websockets-next.server.supported-subprotocols=bearer-token-carrier
quarkus.websockets-next.server.propagate-subprotocol-headers=true

quarkus.websockets-next.server.traffic-logging.enabled=true 
quarkus.websockets-next.server.traffic-logging.text-payload-limit=1000

quarkus.log.category."io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator".level=TRACE
quarkus.log.category."io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator".min-level=TRACE

service.message-service-url=${MESSAGE_SERVICE_URL:http://localhost:8080/messaging/conversations}
service.jwt-secret=${JWT_SECRET}
service.jwt-issuer=chat-delivery-service
