// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (type, name, created_by)
VALUES ($1, $2, $3)
RETURNING id, name, type, created_at, last_message_at, created_by
`

type CreateConversationParams struct {
	Type      ConversationType
	Name      *string
	CreatedBy uuid.UUID
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.Type, arg.Name, arg.CreatedBy)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.LastMessageAt,
		&i.CreatedBy,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations
WHERE id = $1
`

func (q *Queries) DeleteConversation(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteConversation, id)
	return err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, name, type, created_at, last_message_at, created_by FROM conversations
WHERE id = $1
`

func (q *Queries) GetConversationByID(ctx context.Context, id int64) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationByID, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.LastMessageAt,
		&i.CreatedBy,
	)
	return i, err
}

const getPrivateConversationID = `-- name: GetPrivateConversationID :one
SELECT p.conversation_id
FROM participants p
JOIN conversations c ON c.id = p.conversation_id
WHERE c.type = 'private'
AND p.user_uuid IN ($1, $2)
GROUP BY p.conversation_id
HAVING COUNT(*) = 2
LIMIT 1
`

type GetPrivateConversationIDParams struct {
	UserUuid1 uuid.UUID
	UserUuid2 uuid.UUID
}

func (q *Queries) GetPrivateConversationID(ctx context.Context, arg GetPrivateConversationIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getPrivateConversationID, arg.UserUuid1, arg.UserUuid2)
	var conversation_id int64
	err := row.Scan(&conversation_id)
	return conversation_id, err
}

const getUserConversationIDs = `-- name: GetUserConversationIDs :many
SELECT 
    c.id
FROM conversations c
JOIN participants p ON c.id = p.conversation_id
WHERE p.user_uuid = $1
`

func (q *Queries) GetUserConversationIDs(ctx context.Context, userUuid uuid.UUID) ([]int64, error) {
	rows, err := q.db.Query(ctx, getUserConversationIDs, userUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserConversations = `-- name: GetUserConversations :many
SELECT 
    c.id,
    c.type,
    c.created_at,
    c.created_by,
    COALESCE(c.name, (
        SELECT p2.username 
        FROM participants p2 
        WHERE p2.conversation_id = c.id AND p2.user_uuid != $1
        limit 1
    )) AS display_name,
    COALESCE(m.content, '') AS last_message,
    COALESCE(m.sent_at, '1970-01-01 00:00:00+00'::timestamptz) AS sent_at    
    --m.content AS last_message,
    --m.sent_at
FROM conversations c
JOIN participants p ON c.id = p.conversation_id
LEFT JOIN LATERAL (
    SELECT m2.content, m2.sent_at
    FROM messages m2
    WHERE m2.conversation_id = c.id
    ORDER BY m2.id DESC
    LIMIT 1
) m ON true
WHERE p.user_uuid  = $1
ORDER BY m.sent_at DESC
`

type GetUserConversationsRow struct {
	ID          int64
	Type        ConversationType
	CreatedAt   time.Time
	CreatedBy   uuid.UUID
	DisplayName *string
	LastMessage string
	SentAt      time.Time
}

func (q *Queries) GetUserConversations(ctx context.Context, userUuid uuid.UUID) ([]GetUserConversationsRow, error) {
	rows, err := q.db.Query(ctx, getUserConversations, userUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserConversationsRow
	for rows.Next() {
		var i GetUserConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.DisplayName,
			&i.LastMessage,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGroups = `-- name: GetUserGroups :many
SELECT 
    c.id,
    c.name AS group_name,
    c.created_at
FROM conversations c
JOIN participants p 
    ON p.conversation_id = c.id
WHERE p.user_uuid = $1
  AND c.type = 'group'
ORDER BY c.name
`

type GetUserGroupsRow struct {
	ID        int64
	GroupName *string
	CreatedAt time.Time
}

func (q *Queries) GetUserGroups(ctx context.Context, userUuid uuid.UUID) ([]GetUserGroupsRow, error) {
	rows, err := q.db.Query(ctx, getUserGroups, userUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserGroupsRow
	for rows.Next() {
		var i GetUserGroupsRow
		if err := rows.Scan(&i.ID, &i.GroupName, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversationLastMessageAt = `-- name: UpdateConversationLastMessageAt :exec
UPDATE conversations SET last_message_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateConversationLastMessageAt(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateConversationLastMessageAt, id)
	return err
}

const updateConversationName = `-- name: UpdateConversationName :exec
UPDATE conversations
SET name = $1
WHERE id = $2
`

type UpdateConversationNameParams struct {
	Name *string
	ID   int64
}

func (q *Queries) UpdateConversationName(ctx context.Context, arg UpdateConversationNameParams) error {
	_, err := q.db.Exec(ctx, updateConversationName, arg.Name, arg.ID)
	return err
}
