// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (conversation_id, sender_user_uuid, content, client_ts) 
VALUES ($1, $2, $3, $4) RETURNING id, conversation_id, sender_user_uuid, content, sent_at, edited_at, is_deleted, client_ts
`

type CreateMessageParams struct {
	ConversationID int64
	SenderUserUuid uuid.UUID
	Content        string
	ClientTs       *int64
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ConversationID,
		arg.SenderUserUuid,
		arg.Content,
		arg.ClientTs,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderUserUuid,
		&i.Content,
		&i.SentAt,
		&i.EditedAt,
		&i.IsDeleted,
		&i.ClientTs,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
UPDATE messages SET is_deleted = TRUE WHERE id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMessage, id)
	return err
}

const getMessagesByConversation = `-- name: GetMessagesByConversation :many
SELECT 
    m.id,
    m.conversation_id,
    m.content, 
    m.sent_at, 
    m.edited_at,
    m.is_deleted,
    s.username AS sender_username,
    m.sender_user_uuid,
    m.client_ts
FROM messages m 
JOIN participants s ON m.conversation_id = s.conversation_id AND m.sender_user_uuid = s.user_uuid 
JOIN participants v ON v.conversation_id = m.conversation_id AND v.user_uuid = $4
WHERE m.conversation_id = $1 AND m.is_deleted = FALSE
AND m.sent_at > v.joined_at 
ORDER BY m.sent_at DESC 
LIMIT $2 OFFSET $3
`

type GetMessagesByConversationParams struct {
	ConversationID int64
	Limit          int32
	Offset         int32
	UserUuid       uuid.UUID
}

type GetMessagesByConversationRow struct {
	ID             int64
	ConversationID int64
	Content        string
	SentAt         time.Time
	EditedAt       *time.Time
	IsDeleted      bool
	SenderUsername string
	SenderUserUuid uuid.UUID
	ClientTs       *int64
}

func (q *Queries) GetMessagesByConversation(ctx context.Context, arg GetMessagesByConversationParams) ([]GetMessagesByConversationRow, error) {
	rows, err := q.db.Query(ctx, getMessagesByConversation,
		arg.ConversationID,
		arg.Limit,
		arg.Offset,
		arg.UserUuid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesByConversationRow
	for rows.Next() {
		var i GetMessagesByConversationRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Content,
			&i.SentAt,
			&i.EditedAt,
			&i.IsDeleted,
			&i.SenderUsername,
			&i.SenderUserUuid,
			&i.ClientTs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesByConversationCursor = `-- name: GetMessagesByConversationCursor :many
SELECT 
    m.id,
    m.sent_at,
    s.joined_at,
    m.conversation_id,
    m.content, 
    m.sent_at, 
    m.edited_at,
    m.is_deleted,
    s.username AS sender_username,
    m.sender_user_uuid,
    m.client_ts
FROM messages m 
JOIN participants s ON m.conversation_id = s.conversation_id AND m.sender_user_uuid = s.user_uuid
JOIN participants v ON v.conversation_id = m.conversation_id AND v.user_uuid = $2
WHERE m.conversation_id = $3 AND m.is_deleted = FALSE
AND m.id < $4
AND m.sent_at > v.joined_at 
ORDER BY m.sent_at DESC
LIMIT $1
`

type GetMessagesByConversationCursorParams struct {
	Limit          int32
	UserUuid       uuid.UUID
	ConversationID int64
	MessageID      int64
}

type GetMessagesByConversationCursorRow struct {
	ID             int64
	SentAt         time.Time
	JoinedAt       time.Time
	ConversationID int64
	Content        string
	SentAt_2       time.Time
	EditedAt       *time.Time
	IsDeleted      bool
	SenderUsername string
	SenderUserUuid uuid.UUID
	ClientTs       *int64
}

func (q *Queries) GetMessagesByConversationCursor(ctx context.Context, arg GetMessagesByConversationCursorParams) ([]GetMessagesByConversationCursorRow, error) {
	rows, err := q.db.Query(ctx, getMessagesByConversationCursor,
		arg.Limit,
		arg.UserUuid,
		arg.ConversationID,
		arg.MessageID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesByConversationCursorRow
	for rows.Next() {
		var i GetMessagesByConversationCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.SentAt,
			&i.JoinedAt,
			&i.ConversationID,
			&i.Content,
			&i.SentAt_2,
			&i.EditedAt,
			&i.IsDeleted,
			&i.SenderUsername,
			&i.SenderUserUuid,
			&i.ClientTs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessageContent = `-- name: UpdateMessageContent :exec
UPDATE messages SET content = $1, edited_at = CURRENT_TIMESTAMP WHERE id = $2
`

type UpdateMessageContentParams struct {
	Content string
	ID      int64
}

func (q *Queries) UpdateMessageContent(ctx context.Context, arg UpdateMessageContentParams) error {
	_, err := q.db.Exec(ctx, updateMessageContent, arg.Content, arg.ID)
	return err
}
