// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type ConversationType string

const (
	ConversationTypePrivate ConversationType = "private"
	ConversationTypeGroup   ConversationType = "group"
)

func (e *ConversationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConversationType(s)
	case string:
		*e = ConversationType(s)
	default:
		return fmt.Errorf("unsupported scan type for ConversationType: %T", src)
	}
	return nil
}

type NullConversationType struct {
	ConversationType ConversationType
	Valid            bool // Valid is true if ConversationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConversationType) Scan(value interface{}) error {
	if value == nil {
		ns.ConversationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConversationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConversationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConversationType), nil
}

type Conversation struct {
	ID            int64
	Name          *string
	Type          ConversationType
	CreatedAt     time.Time
	LastMessageAt *time.Time
	CreatedBy     uuid.UUID
}

type Message struct {
	ID             int64
	ConversationID int64
	SenderUserUuid uuid.UUID
	Content        string
	SentAt         time.Time
	EditedAt       *time.Time
	IsDeleted      bool
	ClientTs       *int64
}

type Participant struct {
	ID             int64
	ConversationID int64
	UserUuid       uuid.UUID
	Username       string
	IsAdmin        bool
	JoinedAt       time.Time
}
