// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: participants.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const addParticipant = `-- name: AddParticipant :one
INSERT INTO participants (conversation_id, user_uuid, username, is_admin) 
VALUES ($1, $2, $3, $4)
RETURNING id, conversation_id, user_uuid, username, is_admin, joined_at
`

type AddParticipantParams struct {
	ConversationID int64
	UserUuid       uuid.UUID
	Username       string
	IsAdmin        bool
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) (Participant, error) {
	row := q.db.QueryRow(ctx, addParticipant,
		arg.ConversationID,
		arg.UserUuid,
		arg.Username,
		arg.IsAdmin,
	)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserUuid,
		&i.Username,
		&i.IsAdmin,
		&i.JoinedAt,
	)
	return i, err
}

const getConversationMembers = `-- name: GetConversationMembers :many
SELECT id, conversation_id, user_uuid, username, is_admin, joined_at FROM participants WHERE conversation_id = $1
`

func (q *Queries) GetConversationMembers(ctx context.Context, conversationID int64) ([]Participant, error) {
	rows, err := q.db.Query(ctx, getConversationMembers, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Participant
	for rows.Next() {
		var i Participant
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.UserUuid,
			&i.Username,
			&i.IsAdmin,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeParticipant = `-- name: RemoveParticipant :exec
DELETE FROM participants WHERE conversation_id = $1 AND user_uuid = $2
`

type RemoveParticipantParams struct {
	ConversationID int64
	UserUuid       uuid.UUID
}

func (q *Queries) RemoveParticipant(ctx context.Context, arg RemoveParticipantParams) error {
	_, err := q.db.Exec(ctx, removeParticipant, arg.ConversationID, arg.UserUuid)
	return err
}

const updateAdminRole = `-- name: UpdateAdminRole :exec
/*-- name: GetUserConversations :many
SELECT t1.id, t1.name, t1.type, t1.last_message_at 
FROM conversations t1 
JOIN participants t2 ON t1.id = t2.conversation_id 
WHERE t2.user_uuid = $1 
ORDER BY t1.last_message_at DESC;
*/

UPDATE participants SET is_admin = $3 WHERE conversation_id = $1 AND user_uuid = $2
`

type UpdateAdminRoleParams struct {
	ConversationID int64
	UserUuid       uuid.UUID
	IsAdmin        bool
}

func (q *Queries) UpdateAdminRole(ctx context.Context, arg UpdateAdminRoleParams) error {
	_, err := q.db.Exec(ctx, updateAdminRole, arg.ConversationID, arg.UserUuid, arg.IsAdmin)
	return err
}
