// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddParticipant(ctx context.Context, arg AddParticipantParams) (Participant, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	DeleteConversation(ctx context.Context, id int64) error
	DeleteMessage(ctx context.Context, id int64) error
	GetConversationByID(ctx context.Context, id int64) (Conversation, error)
	GetConversationMembers(ctx context.Context, conversationID int64) ([]Participant, error)
	GetMessagesByConversation(ctx context.Context, arg GetMessagesByConversationParams) ([]GetMessagesByConversationRow, error)
	GetUserConversations(ctx context.Context, userUuid uuid.UUID) ([]GetUserConversationsRow, error)
	RemoveParticipant(ctx context.Context, arg RemoveParticipantParams) error
	UpdateAdminRole(ctx context.Context, arg UpdateAdminRoleParams) error
	UpdateConversationLastMessageAt(ctx context.Context, id int64) error
	UpdateConversationName(ctx context.Context, arg UpdateConversationNameParams) error
	UpdateMessageContent(ctx context.Context, arg UpdateMessageContentParams) error
}

var _ Querier = (*Queries)(nil)
