# version: '3.9'

services:

  chat-delivery-service:
    image: quarkus/chat-delivery-service
    container_name: chat-delivery-service
    ports:
      - "8180:8080"
    env_file:
      - ${ENV_FILE:-.env.docker}	  
    environment:
      - JWT_JWK=${JWT_JWK:-REQUIRED}
    networks:
      - chat-demo-net   
networks:
  chat-demo-net:
    # name: chat-demo-net   # same fixed network name
    external: true             