apiVersion: v1
kind: PersistentVolume
metadata:
  name: redpanda-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: "projects/{{ .Values.gcpProjectId }}/zones/us-west1-a/disks/chat-demo-redpanda"
    fsType: ext4
  claimRef:
    name: redpanda-pvc
    namespace: {{ .Release.Namespace }}
