apiVersion: v1
kind: Service
metadata:
  name: redpanda
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: redpanda
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
