# supposed to be smaller than alpine
FROM golang:1.25.5-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -trimpath -ldflags="-s -w" -o app

FROM gcr.io/distroless/base-debian12
COPY --from=build /app/app /app
USER nonroot
EXPOSE 8080
ENTRYPOINT ["/app"]
